builder:
  track: dev

labels:
  app-group: estafette-ci-extensions
  team: estafette-team
  language: golang

version:
  semver:
    major: 0
    minor: 1

stages:
  build:
    image: golang:1.15.0-alpine3.12
    env:
      CGO_ENABLED: 0
      GOOS: linux
      GOGC: off
    commands:
    - go test ./...
    - go build -a -installsuffix cgo -ldflags "-X main.appgroup=${ESTAFETTE_LABEL_APP_GROUP} -X main.app=${ESTAFETTE_GIT_NAME} -X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_GIT_NAME} .

  bake:
    image: extensions/docker:dev
    action: build
    container: helm
    dontExpand:
    - PATH
    inline: |
      FROM alpine/helm:3.3.1

      LABEL maintainer="estafette.io" \
            description="The ${ESTAFETTE_GIT_NAME} component is an Estafette extension to with linting, packaging, testing and adding Helm charts to repositories"

      ENV VERSION="${ESTAFETTE_BUILD_VERSION}" \
          HELM_DIFF_VERSION="v3.1.3" \
          HELM_GCS_VERSION="0.3.6"

      RUN apk add --update --upgrade  --no-cache \
            git \
            bash \
            openssl \
            curl \
          && rm -rf /var/cache/apk/* \
          && wget -O /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/v1.15.1/bin/linux/amd64/kubectl \
          && chmod +x /usr/local/bin/kubectl \
          && mkdir -p ~/.kube ~/.helm/plugins \
          && helm plugin install https://github.com/databus23/helm-diff --version ${HELM_DIFF_VERSION} \
          && helm plugin install https://github.com/hayorov/helm-gcs --version ${HELM_GCS_VERSION} \
          && /root/.local/share/helm/plugins/helm-gcs/bin/helm-gcs \
          && helm plugin list

      # install gcloud sdk, see https://github.com/GoogleCloudPlatform/cloud-sdk-docker/blob/master/alpine/Dockerfile
      ENV PATH="/google-cloud-sdk/bin:$PATH" \
          CLOUD_SDK_VERSION="305.0.0"

      RUN apk --no-cache add \
              python3 \
              py-crcmod \
              bash \
              libc6-compat \
              openssh-client \
              git \
              gnupg \
          && wget -O google-cloud-sdk.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${CLOUD_SDK_VERSION}-linux-x86_64.tar.gz \
          && tar xzf google-cloud-sdk.tar.gz -C / \
          && rm google-cloud-sdk.tar.gz \
          && gcloud config set core/disable_usage_reporting true \
          && gcloud config set component_manager/disable_update_check true \
          && gcloud config set metrics/environment github_docker_image \
          && gcloud --version

      COPY ${ESTAFETTE_GIT_NAME} /

      WORKDIR /estafette-work

      ENV ESTAFETTE_LOG_FORMAT="console"

      ENTRYPOINT ["/${ESTAFETTE_GIT_NAME}"]
    repositories:
    - extensions
    path: ./publish

  check-container:
    parallelStages:
      check-efficiency:
        image: extensions/docker:dev
        action: dive
        container: helm
        repositories:
        - extensions

      vulnerability-scan:
        image: extensions/docker:dev
        action: trivy
        container: helm
        repositories:
        - extensions

  push-to-docker-hub:
    image: extensions/docker:dev
    action: push
    container: helm
    repositories:
    - extensions

  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: estafette
    channels:
    - '#build-status'
    when:
      status == 'succeeded' ||
      status == 'failed'

releases:
  dev:
    triggers:
    - pipeline:
        name: self
        branch: .+
    stages:
      tag-container-image:
        image: extensions/docker:dev
        action: tag
        container: helm
        repositories:
        - extensions
        tags:
        - dev

  beta:
    stages:
      tag-container-image:
        image: extensions/docker:dev
        action: tag
        container: helm
        repositories:
        - extensions
        tags:
        - beta

      slack-notify:
        image: extensions/slack-build-status:dev
        workspace: estafette
        channels:
        - '#build-status'
        when:
          status == 'succeeded' ||
          status == 'failed'

  stable:
    stages:
      tag-container-image:
        image: extensions/docker:dev
        action: tag
        container: helm
        repositories:
        - extensions
        tags:
        - stable
        - latest

      slack-notify:
        image: extensions/slack-build-status:dev
        workspace: estafette
        channels:
        - '#build-status'
        when:
          status == 'succeeded' ||
          status == 'failed'